// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXroQ57bxMsw2efJg2yG9fQgyclsBrqyg',
    appId: '1:990623475684:android:e7a2f0afac3689e220c9f1',
    messagingSenderId: '990623475684',
    projectId: 'dung60th1-b0c7b',
    databaseURL: 'https://dung60th1-b0c7b-default-rtdb.firebaseio.com',
    storageBucket: 'dung60th1-b0c7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTR0U-_gDs1GvAcsQwPnnCN_ee7x8sC10',
    appId: '1:990623475684:ios:976b02dced2c1b6b20c9f1',
    messagingSenderId: '990623475684',
    projectId: 'dung60th1-b0c7b',
    databaseURL: 'https://dung60th1-b0c7b-default-rtdb.firebaseio.com',
    storageBucket: 'dung60th1-b0c7b.appspot.com',
    iosBundleId: 'com.example.tinhTienDienNuocPhongTro',
  );
}
